# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0003_ninjas_dojo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninjas',
            name='dojo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo_ninjas.dojos'),
        ),
    ]
