# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0004_auto_20170920_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninjas',
            old_name='dojo_id',
            new_name='dojo',
        ),
    ]
