# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='', max_length=100, null=True),
        ),
    ]
