# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0009_auto_20170924_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_authors.Books'),
        ),
    ]
